### ISSUE TITLE
nodeunit test/index.js   -----Unhandled rejection Error: ETIMEDOUT

### ISSUE THREAD

**Issue by demonray** [shanelau/rssSpider#3]
[demon@demon-pc:~/rssSpider/rssSpider → master]$ nodeunit test/index.js 

index.js
Unhandled rejection Error: ETIMEDOUT
    at null._onTimeout (/home/demon/rssSpider/rssSpider/node_modules/request/request.js:909:15)
    at Timer.listOnTimeout (timers.js:110:15)

FAILURES: Undone tests (or their setups/teardowns): 
- fetchRSS

To fix this, make sure all tests call test.done()

**Comment by shanelau** [comment]
看问题是链接超时，request模块报错的。
 我刚刚在本地测试是没问题的。  是否有修改  url的值？

**Comment by shanelau** [comment]
@demonray 我给你的使用案例不能运行吗？

**Comment by demonray** [comment]
谢谢回信，没有修改url,你那边测没问题的话，估计是家里网络问题,我再看看


来自 魅族 MX4

-------- 原始邮件 --------
发件人："liu.xing" <notifications@github.com>
时间：周一 3月16日 11:27
收件人：shanelau/rssSpider <rssSpider@noreply.github.com>
抄送：Ray <lei2005826@126.com>
主题：Re: [rssSpider] nodeunit test/index.js   -----Unhandled rejection Error: ETIMEDOUT (#3)

**Comment by shanelau** [comment]
我建议你重新安装  rssspider,

然后执行一下，demo案例， 

```
var spide = require('rssspider');
var url = 'http://www.bigertech.com/rss';
spide.fetchRss(url).then(function(data){
        console.log(data); // rss  post list
});
```

**Comment by demonray** [comment]
可以了，家里网络问题
