### ISSUE TITLE
当我node更新到4.2.1后，这个模块就出问题啦。

### ISSUE THREAD

**Issue by anchengjian** [shanelau/rssSpider#8]
当我node更新到4.2.1后，这个模块就出问题啦。
贴部分错误：
>
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "rssspider"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
>
npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

怀疑是作者的包里用的contextify错误。
最后，为作者的贡献表示感谢～

**Comment by shanelau** [comment]
Sorry rssspider 还没有做 4.2的兼容。 我会花时间改成4.2的版本

**Comment by shanelau** [comment]
@anchengjian 已经解决了
